version: '3'
services:
  app:
    image: elixir
    ports:
      - 4000
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
