# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.6
      - image: postgres
        environment:
          POSTGRES_USER: postgres
      
    environment:
      - DB_HOSTNAME: "localhost"

    working_directory: ~/repo
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix ecto.create
      - run: mix ecto.migrate
      - run: mix test
